spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud_cell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 106.14.122.223
    port: 5672
    username: admin
    password: zc12138
  redis:
    host: 106.14.122.223
    port: 6379
  zipkin:
    base-url: http://106.14.122.223:9411/
  sleuth:
    sampler:
      percentage: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
env:
  dev
